---
- name: Configure CSR1kv
  hosts: CSR1kv
  gather_facts: no
  connection: local
  tasks:
    - name: Configure hostname
      ios_config:
        lines:
          - username {{ username }} password {{ password }}
  vars_prompt:
    - name: username
      prompt: Username 
      private: false
    - name: password
      prompt: Password 
      private: true
