---
- name: Configure DHCP Server on CSR1kv
  hosts: CSR1kv
  connection: local
  gather_facts: no
  tasks:
    - name: Create DHCP Pool
      ios_config:
        lines:
          - network 192.168.56.0 255.255.255.0
          - default-router 192.168.56.128
          - dns-server 8.8.8.8
          - lease 0 8
        parents: ip dhcp pool LAN
